# Generated by Django 3.0.5 on 2020-04-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level_five_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='porfile_image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
