# Generated by Django 3.0.5 on 2020-04-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level_five_app', '0002_auto_20200426_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='porfile_image',
            new_name='profile_image',
        ),
    ]
